import { categories } from "./categories";

type TProduct = {
  id: number;
  title: string;
  category: string;
  description: string;
  price: number;
  rating: number;
  image: string;
}[];

export const products: TProduct = [
  {
    id: 1,
    title: "Philips",
    category: "electronics",
    description:
      "Over-ear wireless Bluetooth headphones with noise-canceling features.",
    price: 45876,
    rating: 4.5,
    image: "/images/air fryer (1).jpeg",
  },
  {
    id: 2,
    title: "Air Fryer",
    category: "electronics",
    description:
      "Latest model with 64GB storage, 5G connectivity, and 12MP camera.",
    price: 52734,
    rating: 4.7,
    image: "/images/air fryer (2).jpeg",
  },
  {
    id: 3,
    title: "Fryer Philips",
    category: "Electroplating",
    description: "Rechargeable Fryer Philips with 3 modes and 2 brush heads.",
    price: 32150,
    rating: 4.3,
    image: "/images/air fryer (3).jpeg",
  },
  {
    id: 5,
    title: "Oven",
    category: "electronics",
    description: "Oven with a 3-inch LCD display and 4x optical zoom.",
    price: 60744,
    rating: 4.2,
    image: "/images/angeleno.jpeg",
  },
  {
    id: 6,
    title: "LED Desk Lamp",
    category: "crockery",
    description:
      "Adjustable LED desk lamp with 5 brightness levels and touch control.",
    price: 29162,
    rating: 4.5,
    image: "/images/angeleno (2).jpeg",
  },
  {
    id: 7,
    title: "Air Purifier",
    category: "crockery",
    description:
      "Compact air purifier with HEPA filter, removes 99.97% of airborne particles.",
    price: 54289,
    rating: 4.8,
    image: "/images/anleno.jpeg",
  },
  {
    id: 8,
    title: "Cordless Vacuum Cleaner",
    category: "Home Appliances",
    description:
      "Cordless vacuum cleaner with powerful suction and multiple attachments.",
    price: 39482,
    rating: 4.4,
    image: "/images/bred (1).jpeg",
  },
  {
    id: 9,
    title: "Smart Fitness Tracker",
    category: "Health & Fitness",
    description:
      "Water-resistant fitness tracker with heart rate monitoring and step tracking.",
    price: 26890,
    rating: 4.1,
    image: "/images/bred (2).jpeg",
  },
  {
    id: 10,
    title: "Stainless Steel Cookware Set",
    category: "dinnerSet",
    description:
      "10-piece stainless steel cookware set with tempered glass lids.",
    price: 61347,
    rating: 4.6,
    image: "/images/bred (3).jpeg",
  },
  {
    id: 13,
    title: "Leather Wallet",
    category: "Fashion",
    description:
      "Genuine leather wallet with multiple card slots and a coin pocket.",
    price: 21120,
    rating: 4.4,
    image: "/images/bred (6).jpeg",
  },
  {
    id: 15,
    title: "Smart Thermostat",
    category: "chinaSet",
    description:
      "Wi-Fi enabled smart thermostat for energy-saving and remote control.",
    price: 56892,
    rating: 4.7,
    image: "/images/chainak (2).jpeg",
  },
  {
    id: 21,
    title: "Outdoor Patio Furniture Set",
    category: "Electroplating",
    description:
      "4-piece outdoor patio furniture set with cushions and a coffee table.",
    price: 48273,
    rating: 4.4,
    image: "/images/chainak (8).jpeg",
  },
  {
    id: 22,
    title: "Memory Foam Pillow",
    category: "chinaSet",
    description: "Orthopedic memory foam pillow for neck and spine support.",
    price: 31956,
    rating: 4.3,
    image: "/images/chainak orignal (1).jpeg",
  },
  {
    id: 23,
    title: "best full china set",
    category: "Electroplating",
    description:
      "Coffee maker with built-in grinder and programmable brewing options.",
    price: 61243,
    rating: 4.6,
    image: "/images/chainak orignal (2).jpeg",
  },
  {
    id: 25,
    title: "Kitchen Knife Set",
    category: "giftware",
    description:
      "Premium 8-piece kitchen knife set with ergonomic handles and a block.",
    price: 47356,
    rating: 4.6,
    image: "/images/chainak orignal (4).jpeg",
  },
  {
    id: 28,
    title: "Ceramic Pie Dish",
    category: "Electroplating",
    description:
      "Water-resistant wireless earbuds with noise cancellation and up to 8 hours battery life.",
    price: 37372,
    rating: 4.7,
    image: "/images/chainak orignal (6).jpeg",
  },
  {
    id: 32,
    title: "cahina set",
    category: "chinaSet",
    description: "55-inch LED TV with 4K resolution and smart functionality.",
    price: 57429,
    rating: 4.6,
    image: "/images/chainak orignal (10).jpeg",
  },
  {
    id: 33,
    title: "Non-stick Frying Pan",
    category: "cookware",
    description:
      "Spacious 4-person camping tent with waterproof and durable material.",
    price: 52349,
    rating: 4.7,
    image: "/images/chainak orignal (11).jpeg",
  },
  {
    id: 34,
    title: "Calphalon Contemporary Non-Stick Fry Pan",
    category: "cookware",
    description: "Portable solar charger for phones and small electronics.",
    price: 30725,
    rating: 4.2,
    image: "/images/cooker.jpeg",
  },
  {
    id: 35,
    title: "Cuisinart Chef's",
    category: "cookware",
    description:
      "King-size memory foam mattress with breathable, cooling technology.",
    price: 62149,
    rating: 4.8,
    image: "/images/cookware (1).jpeg",
  },
  {
    id: 36,
    title: "GreenPan Valencia Pro Non-Stick Frying Pan",
    category: "cookware",
    description:
      "Wireless in-ear earbuds with noise-canceling technology and 10 hours battery life.",
    price: 49988,
    rating: 4.6,
    image: "/images/cookware (2).jpeg",
  },
  {
    id: 37,
    title: "Cleansing Facial Brush",
    category: "Electroplating",
    description:
      "Waterproof facial cleansing brush with multiple speed settings.",
    price: 23561,
    rating: 4.5,
    image: "/images/cookware (3).jpeg",
  },
  {
    id: 38,
    title: "Robot Vacuum Cleaner",
    category: "Home Appliances",
    description:
      "Smart robotic vacuum cleaner with mapping and scheduling features.",
    price: 62638,
    rating: 4.7,
    image: "/images/cookware (4).jpeg",
  },
  {
    id: 39,
    title: "Smart LED Bulbs",
    category: "Home Appliances",
    description:
      "Wi-Fi enabled LED bulbs that can be controlled with your smartphone.",
    price: 29640,
    rating: 4.6,
    image: "/images/cookware (5).jpeg",
  },
  {
    id: 40,
    title: "Electrical cup",
    category: "luxurious",
    description:
      "Ergonomic office chair with adjustable height and lumbar support.",
    price: 23561,
    rating: 4.4,
    image: "/images/cup style.jpeg",
  },
  {
    id: 41,
    title: "Smart cup",
    category: "electronics",
    description:
      "Streaming stick that turns any TV into a smart TV with access to popular streaming services.",
    price: 18237,
    rating: 4.5,
    image: "/images/cup style2.jpeg",
  },
  {
    id: 42,
    title: "Cordless Hair Curler",
    category: "electronics",
    description:
      "Rechargeable cordless hair curler with ceramic barrel and heat settings.",
    price: 24532,
    rating: 4.4,
    image: "/images/cup.jpeg",
  },
  {
    id: 46,
    title: "Melamine plate",
    category: categories.crockery,
    description: "Foldable electric scooter with up to 15 miles per charge.",
    price: 24532,
    rating: 4.5,
    image: "/images/diner-plate.jpeg",
  },
  {
    id: 47,
    title: "classical plate",
    category: categories.crockery,
    description:
      "Compact ceramic space heater with 2 adjustable heat settings.",
    price: 28415,
    rating: 4.3,
    image: "/images/diner-plate2.jpeg",
  },
  {
    id: 48,
    title: "Can Opener",
    category: categories.crockery,
    description: "Automatic electric can opener for easy and safe can opening.",
    price: 21900,
    rating: 4.6,
    image: "/images/dinner-plate3.jpeg",
  },
  {
    id: 49,
    title: "Fitness Resistance",
    category: categories.dinnerSet,
    description:
      "Set of resistance bands for home workouts, includes multiple resistance levels.",
    price: 27950,
    rating: 4.5,
    image: "/images/fullSet (1).jpeg",
  },
  {
    id: 50,
    title: "Backpack for Travel",
    category: categories.dinnerSet,
    description:
      "Durable travel backpack with multiple compartments and laptop sleeve.",
    price: 33460,
    rating: 4.6,
    image: "/images/fullSet (2).jpeg",
  },
  {
    id: 51,
    title: "Table set",
    category: categories.Electroplating,
    description:
      "Modern table lamp with adjustable brightness and sleek design.",
    price: 17950,
    rating: 4.4,
    image: "/images/fullSet (3).jpeg",
  },
  {
    id: 52,
    title: "Air Fryer",
    category: categories.dinnerSet,
    description:
      "Healthy cooking with this air fryer that fries with little or no oil.",
    price: 38200,
    rating: 4.7,
    image: "/images/teaa (1).jpeg",
  },
  {
    id: 53,
    title: "Bluetooth Headset",
    category: categories.electronics,
    description:
      "Comfortable Bluetooth headset for hands-free calls and music.",
    price: 31950,
    rating: 4.4,
    image: "/images/fullSet (5).jpeg",
  },
  {
    id: 54,
    title: "Memory Foam Slippers",
    category: "Fashion",
    description: "Soft and cushioned memory foam slippers for indoor comfort.",
    price: 25900,
    rating: 4.6,
    image: "/images/fullSet (6).jpeg",
  },
  {
    id: 55,
    title: "Smart Mirror",
    category: "Home Appliances",
    description:
      "Smart mirror with LED lighting and touch controls for beauty routines.",
    price: 42000,
    rating: 4.5,
    image: "/images/fullSet (7).jpeg",
  },
  {
    id: 56,
    title: "Cookbook Set",
    category: categories.dinnerSet,
    description:
      "Set of best-selling cookbooks for healthy, easy-to-make recipes.",
    price: 24860,
    rating: 4.7,
    image: "/images/fullSet (8).jpeg",
  },
  {
    id: 57,
    title: "cleaner",
    category: categories.electronics,
    description: "Wireless keyboard and mouse combo for home or office use.",
    price: 19950,
    rating: 4.3,
    image: "/images/hitachi (1).jpeg",
  },
  {
    id: 58,
    title: "Smart Plugs with Energy Monitoring",
    category: "Home Appliances",
    description:
      "Smart plugs that monitor energy usage and can be controlled remotely.",
    price: 21820,
    rating: 4.6,
    image: "/images/hitachi (2).jpeg",
  },
  {
    id: 59,
    title: "Telescope for Beginners",
    category: categories.Electroplating,
    description: "Beginner-friendly telescope with easy setup and clear views.",
    price: 28950,
    rating: 4.4,
    image: "/images/hitachi (3).jpeg",
  },
  {
    id: 60,
    title: "Pet Water Fountain",
    category: "Pets",
    description:
      "Automatic water fountain for pets with a large capacity and easy to clean.",
    price: 32900,
    rating: 4.5,
    image: "/images/hitachi.jpeg",
  },
  {
    id: 61,
    title: "Indoor Plant Care Kit",
    category: "Home & Garden",
    description:
      "Plant care kit with tools and accessories for indoor gardening.",
    price: 19560,
    rating: 4.6,
    image: "/images/home-hero.jpeg",
  },
  {
    id: 62,
    title: "Dinner set",
    category: categories.dinnerSet,
    description:
      "Compact and portable solar panel charger for outdoor adventures.",
    price: 26750,
    rating: 4.3,
    image: "/images/home-hero1.jpeg",
  },
  {
    id: 63,
    title: "Adjustable Weight Bench",
    category: categories.Electroplating,
    description: "Sturdy adjustable weight bench for home gym use.",
    price: 33520,
    rating: 4.6,
    image: "/images/home-hero2.jpeg",
  },
  {
    id: 64,
    title: "best china set",
    category: categories.chinaSet,
    description:
      "Create homemade ice cream with this easy-to-use electric ice cream maker.",
    price: 24130,
    rating: 4.7,
    image: "/images/home-hero3.jpeg",
  },
  {
    id: 65,
    title: "Home spoon Set",
    category: categories.Electroplating,
    description:
      "Complete home spoon set including dumbbells, resistance bands, and yoga mat.",
    price: 29990,
    rating: 4.4,
    image: "/images/home-hero4.jpeg",
  },
  {
    id: 66,
    title: "Digital Food Scale",
    category: categories.dinnerSet,
    description:
      "Accurate digital kitchen scale for measuring ingredients and portion control.",
    price: 17560,
    rating: 4.3,
    image: "/images/home-hero5.jpeg",
  },
  {
    id: 67,
    title: "Pet Bed",
    category: "Pets",
    description:
      "Cozy and soft pet bed for dogs or cats, easy to wash and maintain.",
    price: 27850,
    rating: 4.6,
    image: "/images/home-hero6.jpeg",
  },
  {
    id: 68,
    title: "Wall Art Prints",
    category: categories.crockery,
    description: "Set of 3 abstract wall art prints for modern home decor.",
    price: 20500,
    rating: 4.5,
    image: "/images/home-hero7.jpeg",
  },
  {
    id: 69,
    title: "LED Strip Lights",
    category: categories.crockery,
    description:
      "Color-changing LED strip lights for mood lighting and decorations.",
    price: 19500,
    rating: 4.7,
    image: "/images/home-hero9.jpeg",
  },
  {
    id: 70,
    title: "Coffee Maker",
    category: categories.luxurious,
    description:
      "Durable coffee maker with fitness tracking and notifications.",
    price: 20890,
    rating: 4.4,
    image: "/images/kenwood-electric-kettle.jpeg",
  },
  {
    id: 71,
    title: "Ceramic Coffee Mug",
    category: categories.luxurious,
    description:
      "Classic ceramic coffee mug with a 12 oz capacity, microwave safe.",
    price: 19250,
    rating: 4.6,
    image: "/images/kettle (1).jpeg",
  },
  {
    id: 72,
    title: "",
    category: categories.luxurious,
    description:
      "Adjustable smartphone stand for hands-free viewing and video calls.",
    price: 22980,
    rating: 4.4,
    image: "/images/kettle (2).jpeg",
  },
  {
    id: 73,
    title: "Camping Stove",
    category: categories.Electroplating,
    description: "Portable camping stove with windscreen and adjustable flame.",
    price: 24320,
    rating: 4.7,
    image: "/images/max plate2.jpeg",
  },
  {
    id: 74,
    title: "Portable Fire Pit",
    category: categories.Electroplating,
    description:
      "Compact and portable fire pit for camping, backyard, and outdoor use.",
    price: 30260,
    rating: 4.5,
    image: "/images/max-plate (2).jpeg",
  },
  {
    id: 75,
    title: "Laptop Cooling Pad",
    category: categories.electronics,
    description:
      "Laptop cooling pad with adjustable fan speed and ergonomic design.",
    price: 21930,
    rating: 4.3,
    image: "/images/max-plate.jpeg",
  },
  {
    id: 78,
    title: "oven",
    category: categories.electronics,
    description: "oven for stretching and improving flexibility.",
    price: 19099,
    rating: 4.5,
    image: "/images/oven (2).jpeg",
  },
  // {
  //   id: 79,
  //   title: "",
  //   category: categories.dinnerSet,
  //   description:
  //     "Electric pressure cooker with multiple cooking presets and slow cook function.",
  //   price: 89.99,
  //   rating: 4.6,
  //   image: "/images/oven (2).jpeg",
  // },
  {
    id: 80,
    title: "Pill Organizer",
    category: categories.electronics,
    description:
      "7-day pill organizer for vitamins and medications, portable and easy to use.",
    price: 5999,
    rating: 4.3,
    image: "/images/oven (3).jpeg",
  },
  {
    id: 81,
    title: "Crokery plate",
    category: categories.crockery,
    description: "Classic Crokery plate with a 12 oz capacity, microwave safe.",
    price: 2599,
    rating: 4.6,
    image: "/images/sk-plate.jpeg",
  },
  {
    id: 82,
    title: "china plate",
    category: categories.crockery,
    description:
      "Adjustable china plate for hands-free viewing and video calls.",
    price: 15999,
    rating: 4.4,
    image: "/images/sk-plate2.jpeg",
  },
  {
    id: 83,
    title: "Ceramic white rise Plate",
    category: categories.crockery,
    description: "Portable camping stove with windscreen and adjustable flame.",
    price: 22999,
    rating: 4.7,
    image: "/images/sk-plate3.jpeg",
  },
  {
    id: 84,
    title: "Portable Fire plate",
    category: categories.crockery,
    description:
      "Compact and portable fire pit for camping, backyard, and outdoor use.",
    price: 32999,
    rating: 4.5,
    image: "/images/soup-set.jpeg",
  },
  {
    id: 85,
    title: "Spoon set",
    category: categories.crockery,
    description: "Spoon set with adjustable fan speed and ergonomic design.",
    price: 24299,
    rating: 4.3,
    image: "/images/spoonset (1).jpeg",
  },
  {
    id: 86,
    title: "Personal Blender",
    category: categories.Electroplating,
    description:
      "Compact personal blender for smoothies and shakes, easy to clean.",
    price: 29399,
    rating: 4.6,
    image: "/images/talmas (3).jpeg",
  },
  {
    id: 87,
    title: "Food Processor",
    category: categories.giftware,
    description:
      "Multi-function food processor with multiple blades for chopping, slicing, and grating.",
    price: 27999,
    rating: 4.4,
    image: "/images/talmas (2).jpeg",
  },
  {
    id: 88,
    title: "Portable Fire plate",
    category: categories.crockery,
    description:
      "Portable Fire plate for stretching and improving flexibility.",
    price: 41999,
    rating: 4.5,
    image: "/images/tea set (2).jpeg",
  },
  {
    id: 90,
    title: "Pill Organizer",
    category: "Health & Fitness",
    description:
      "7-day pill organizer for vitamins and medications, portable and easy to use.",
    price: 39399,
    rating: 4.3,
    image: "/images/vacume.jpeg",
  },
  {
    id: 91,
    title: "Portable Fire Plate",
    category: categories.crockery,
    description:
      "Portable Fire plate for stretching and improving flexibility.",
    price: 41999,
    rating: 4.5,
    image: "/images/tea set (2).jpeg",
  },
  {
    id: 92,
    title: "Pill Organizer",
    category: categories.healthFitness,
    description:
      "7-day pill organizer for vitamins and medications, portable and easy to use.",
    price: 39399,
    rating: 4.3,
    image: "/images/vacume.jpeg",
  },
  {
    id: 93,
    title: "Smart Water Bottle",
    category: categories.healthFitness,
    description:
      "Smart water bottle with hydration reminders and temperature control.",
    price: 25999,
    rating: 4.6,
    image: "/images/waterbottle.jpeg",
  },
  {
    id: 94,
    title: "Resistance Bands Set",
    category: categories.healthFitness,
    description: "Set of 5 resistance bands for strength training and toning.",
    price: 1999,
    rating: 4.7,
    image: "/images/resistance_bands.jpeg",
  },
  {
    id: 95,
    title: "Yoga Mat",
    category: categories.healthFitness,
    description:
      "Durable yoga mat with non-slip surface for all fitness levels.",
    price: 2499,
    rating: 4.8,
    image: "/images/yoga_mat.jpeg",
  },
  {
    id: 96,
    title: "Electric Massage Gun",
    category: categories.healthFitness,
    description:
      "Deep tissue massage gun for muscle relaxation and pain relief.",
    price: 7999,
    rating: 4.4,
    image: "/images/massage_gun.jpeg",
  },
  {
    id: 97,
    title: "Electric dry Iron",
    category: categories.healthFitness,
    description:
      "High-density foam roller for muscle recovery and flexibility.",
    price: 2999,
    rating: 4.6,
    image: "/images/foam_roller.jpeg",
  },
  {
    id: 98,
    title: "Electric Kettle",
    category: categories.kitchenAppliances,
    description: "Fast-boiling electric kettle with automatic shutoff feature.",
    price: 2999,
    rating: 4.3,
    image: "/images/electric_kettle.jpeg",
  },
  {
    id: 99,
    title: "Blender",
    category: categories.kitchenAppliances,
    description: "Powerful blender for smoothies, soups, and more.",
    price: 4999,
    rating: 4.5,
    image: "/images/bl.jpeg",
  },
  {
    id: 100,
    title: "Coffee Maker",
    category: categories.kitchenAppliances,
    description:
      "Coffee maker with built-in grinder for fresh coffee every morning.",
    price: 7999,
    rating: 4.7,
    image: "/images/coffee_maker.jpeg",
  },
  {
    id: 101,
    title: "Smart Fitness Tracker",
    category: categories.healthFitness,
    description: "Track your fitness goals with this smart fitness tracker.",
    price: 5999,
    rating: 4.5,
    image: "/images/fitness_tracker.jpeg",
  },
  {
    id: 102,
    title: "Electric Juicer",
    category: categories.kitchenAppliances,
    description:
      "Quickly juice fruits and vegetables with this electric juicer.",
    price: 4999,
    rating: 4.3,
    image: "/images/electric_juicer.jpeg",
  },
  {
    id: 103,
    title: "Cookware",
    category: categories.kitchenAppliances,
    description: "Compact Cookware for easy indoor grilling.",
    price: 7999,
    rating: 4.6,
    image: "/images/Cookware.jpeg",
  },
  {
    id: 104,
    title: "Cookware Set",
    category: categories.kitchenware,
    description: "Non-stick cookware set with all the essential kitchen tools.",
    price: 12999,
    rating: 4.8,
    image: "/images/cok2.jpeg",
  },
  {
    id: 105,
    title: "Nonstick Frying Pan",
    category: categories.kitchenware,
    description: "Durable nonstick frying pan for easy cooking and cleaning.",
    price: 2999,
    rating: 4.5,
    image: "/images/jus.jpeg",
  },
  {
    id: 106,
    title: "Feenik",
    category: categories.kitchenAppliances,
    description:
      "Compact microwave oven with multiple settings for quick meals.",
    price: 6999,
    rating: 4.7,
    image: "/images/microwave_oven.jpeg",
  },
  {
    id: 107,
    title: "Rice Cooker",
    category: categories.kitchenAppliances,
    description: "Perfectly cook rice with this easy-to-use rice cooker.",
    price: 4999,
    rating: 4.4,
    image: "/images/cok.jpeg",
  },
  {
    id: 108,
    title: "Dishwasher",
    category: categories.kitchenAppliances,
    description: "High-efficiency dishwasher for quick and easy cleaning.",
    price: 19999,
    rating: 4.7,
    image: "/images/dishwasher.jpeg",
  },
  {
    id: 109,
    title: "Spoon Set",
    category: categories.kitchenAppliances,
    description: "Compact spoon set for perfect test every time.",
    price: 1999,
    rating: 4.5,
    image: "/images/spoon.jpeg",
  },
  {
    id: 110,
    title: "Coffee Grinder",
    category: categories.kitchenAppliances,
    description: "Grind fresh coffee beans with this electric coffee grinder.",
    price: 3999,
    rating: 4.6,
    image: "/images/coffee_grinder.jpeg",
  },
  {
    id: 111,
    title: "Disbin",
    category: categories.homeAppliances,
    description: "Clean the air in your home with this HEPA air purifier.",
    price: 10999,
    rating: 4.8,
    image: "/images/dis.jpeg",
  },
  {
    id: 112,
    title: "Smart Thermostat",
    category: categories.homeAppliances,
    description:
      "Control the temperature of your home remotely with this smart thermostat.",
    price: 7999,
    rating: 4.7,
    image: "/images/smart.jpeg",
  },
  {
    id: 113,
    title: "Daynasty",
    category: categories.homeAppliances,
    description: "Efficient Daynasty for quick warmth during winter.",
    price: 4999,
    rating: 4.4,
    image: "/images/electric_heater.jpeg",
  },
  {
    id: 114,
    title: "Dehumidifier",
    category: categories.homeAppliances,
    description:
      "Reduce humidity and improve air quality with this dehumidifier.",
    price: 7999,
    rating: 4.5,
    image: "/images/dehumidifier.jpeg",
  },
  {
    id: 115,
    title: "Smart Light Bulb",
    category: categories.homeAppliances,
    description:
      "Control your home's lighting remotely with this smart light bulb.",
    price: 1999,
    rating: 4.6,
    image: "/images/smart_light_bulb.jpeg",
  },
  {
    id: 116,
    title: "Vacuum set",
    category: categories.homeAppliances,
    description:
      "Smart vacuum cleaner for effortless cleaning around the house.",
    price: 15999,
    rating: 4.8,
    image: "/images/vacuum_cleaner.jpeg",
  },
  {
    id: 117,
    title: "china tea set",
    category: categories.homeAppliances,
    description: "Portable electric fan for cooling during hot days.",
    price: 2999,
    rating: 4.5,
    image: "/images/electric_fan.jpeg",
  },
  {
    id: 118,
    title: "Smart Plugs",
    category: categories.homeAppliances,
    description: "Control your appliances remotely with these smart plugs.",
    price: 1999,
    rating: 4.7,
    image: "/images/set.jpeg",
  },
  {
    id: 119,
    title: "Electric Grill Pan",
    category: categories.kitchenAppliances,
    description: "Non-stick grill pan for cooking meats and vegetables.",
    price: 4999,
    rating: 4.3,
    image: "/images/dis2.jpeg",
  },
  {
    id: 120,
    title: "Tupperware Set",
    category: categories.kitchenware,
    description: "Durable and air-tight tupperware set for storing food.",
    price: 3499,
    rating: 4.5,
    image: "/images/cok2.jpeg",
  },
  {
    id: 121,
    title: "Kitchen Knife Set",
    category: categories.kitchenware,
    description: "Professional kitchen knife set with ergonomic handles.",
    price: 6999,
    rating: 4.6,
    image: "/images/iron.jpeg",
  },
  {
    id: 122,
    title: "Electric Pressure Cooker",
    category: categories.kitchenAppliances,
    description: "Quickly cook meals with this electric pressure cooker.",
    price: 8999,
    rating: 4.7,
    image: "/images/cok2.jpeg",
  },
  {
    id: 123,
    title: "Oven Toaster",
    category: categories.kitchenAppliances,
    description: "Toaster oven for baking and grilling in a compact size.",
    price: 4999,
    rating: 4.4,
    image: "/images/spoon.jpeg",
  },
  {
    id: 124,
    title: "Hand Blender",
    category: categories.kitchenAppliances,
    description: "Blend soups, smoothies, and sauces with this hand blender.",
    price: 2999,
    rating: 4.3,
    image: "/images/hand_blender.jpeg",
  },
  {
    id: 125,
    title: "New china set",
    category: categories.kitchenAppliances,
    description: "Cook delicious meals slowly with this slow cooker.",
    price: 7999,
    rating: 4.7,
    image: "/images/slow_cooker.jpeg",
  },
  {
    id: 126,
    title: "Steamer",
    category: categories.kitchenAppliances,
    description: "Steam vegetables and fish for healthy cooking.",
    price: 3999,
    rating: 4.6,
    image: "/images/steamer.jpeg",
  },
  {
    id: 127,
    title: "Blender",
    category: categories.kitchenAppliances,
    description: "High-speed blender for smoothies, shakes, and more.",
    price: 5999,
    rating: 4.5,
    image: "/images/hot2.jpeg",
  },
  {
    id: 128,
    title: "Food Processor",
    category: categories.kitchenAppliances,
    description:
      "Multi-function food processor for chopping, slicing, and dicing.",
    price: 8999,
    rating: 4.6,
    image: "/images/food_processor.jpeg",
  },
  {
    id: 129,
    title: "Toaster Oven",
    category: categories.kitchenAppliances,
    description: "Versatile toaster oven with multiple cooking functions.",
    price: 6999,
    rating: 4.4,
    image: "/images/toaster_oven.jpeg",
  },
  {
    id: 130,
    title: "Maker",
    category: categories.kitchenAppliances,
    description: "Quickly make sandwiches with this electric sandwich maker.",
    price: 2999,
    rating: 4.3,
    image: "/images/cup4.jpeg",
  },
  {
    id: 131,
    title: "Electric Kettle",
    category: categories.kitchenAppliances,
    description: "Boil water quickly with this efficient electric kettle.",
    price: 2999,
    rating: 4.5,
    image: "/images/electric_kettle.jpeg",
  },
  {
    id: 132,
    title: "Milk Frother",
    category: categories.kitchenAppliances,
    description: "Create frothy milk for your coffee or cappuccinos.",
    price: 2499,
    rating: 4.7,
    image: "/images/hot.jpeg",
  },
  {
    id: 133,
    title: "Coffee Maker",
    category: categories.kitchenAppliances,
    description: "Brew your favorite coffee quickly with this coffee maker.",
    price: 4999,
    rating: 4.6,
    image: "/images/coffee_maker.jpeg",
  },
  {
    id: 134,
    title: "Popcorn Maker",
    category: categories.kitchenAppliances,
    description: "Make fresh popcorn in minutes with this popcorn maker.",
    price: 2499,
    rating: 4.4,
    image: "/images/popcorn_maker.jpeg",
  },
  {
    id: 135,
    title: "Cordless Handheld Vacuum",
    category: categories.homeAppliances,
    description: "Portable, lightweight cordless vacuum for easy cleaning.",
    price: 3999,
    rating: 4.7,
    image: "/images/handheld_vacuum.jpeg",
  },
  {
    id: 136,
    title: "cookware",
    category: categories.homeAppliances,
    description: "Keep an eye on your home with this smart security camera.",
    price: 9999,
    rating: 4.8,
    image: "/images/security_camera.jpeg",
  },
  {
    id: 137,
    title: "Robot Vacuum Cleaner",
    category: categories.homeAppliances,
    description:
      "Let the robot do the cleaning with this automatic vacuum cleaner.",
    price: 15999,
    rating: 4.6,
    image: "/images/cookware (4).jpeg",
  },
  {
    id: 138,
    title: "Ceiling Spoon",
    category: categories.homeAppliances,
    description: "Cool your room with this energy-efficient ceiling fan.",
    price: 4999,
    rating: 4.4,
    image: "/images/ceiling_fan.jpeg",
  },
  {
    id: 139,
    title: "Smart Plug",
    category: categories.homeAppliances,
    description: "Control any appliance remotely with this smart plug.",
    price: 1499,
    rating: 4.7,
    image: "/images/smart_plug.jpeg",
  },
  {
    id: 140,
    title: "Indoor Heater",
    category: categories.homeAppliances,
    description: "Keep warm during the winter months with this indoor heater.",
    price: 3999,
    rating: 4.3,
    image: "/images/indoor_heater.jpeg",
  },
  {
    id: 141,
    title: "Electric iron",
    category: categories.homeAppliances,
    description:
      "Stay cool and comfortable with this portable air conditioner.",
    price: 13999,
    rating: 4.7,
    image: "/images/portable_air_conditioner.jpeg",
  },
  {
    id: 142,
    title: "Electric Blanket",
    category: categories.homeAppliances,
    description: "Stay cozy with this electric blanket during the cold nights.",
    price: 6999,
    rating: 4.5,
    image: "/images/electric_blanket.jpeg",
  },
  {
    id: 143,
    title: "Tea set",
    category: categories.homeAppliances,
    description: "Optimize your energy usage with this Tea set.",
    price: 7999,
    rating: 4.6,
    image: "/images/tea set.jpeg",
  },
  {
    id: 144,
    title: "Desk talmas",
    category: categories.homeAppliances,
    description: "Efficient LED desk lamp with adjustable brightness.",
    price: 2499,
    rating: 4.4,
    image: "/images/jj.jpeg",
  },
  {
    id: 145,
    title: "Spoon",
    category: categories.healthFitness,
    description: "Whiten your teeth with this powerful electric toothbrush.",
    price: 4999,
    rating: 4.5,
    image: "/images/electric_toothbrush.jpeg",
  },
  {
    id: 146,
    title: "Yoga Mat",
    category: categories.sportsFitness,
    description:
      "Non-slip yoga mat for better grip and comfort during workouts.",
    price: 1999,
    rating: 4.6,
    image: "/images/yoga_mat.jpeg",
  },
  {
    id: 147,
    title: "Dumbbells Set",
    category: categories.sportsFitness,
    description: "Set of adjustable dumbbells for strength training at home.",
    price: 7999,
    rating: 4.7,
    image: "/images/dumbbells_set.jpeg",
  },
  {
    id: 148,
    title: "Exercise cole",
    category: categories.sportsFitness,
    description: "Get fit at home with this sturdy exercise bike.",
    price: 11999,
    rating: 4.6,
    image: "/images/exercise_bike.jpeg",
  },
  {
    id: 149,
    title: "Resistance Bands",
    category: categories.sportsFitness,
    description:
      "Set of resistance bands for strength and flexibility training.",
    price: 1499,
    rating: 4.4,
    image: "/images/WhatsApp Image 2024-12-03 at 9.34.42 PM (1).jpeg",
  },
  {
    id: 150,
    title: "Treadmill",
    category: categories.sportsFitness,
    description: "Foldable treadmill for running at home.",
    price: 24999,
    rating: 4.7,
    image: "/images/treadmill.jpeg",
  },
  {
    id: 151,
    title: "Kettlebell Set",
    category: categories.sportsFitness,
    description: "Versatile kettlebell set for home workouts.",
    price: 4999,
    rating: 4.6,
    image: "/images/kettlebell_set.jpeg",
  },
  {
    id: 152,
    title: "Fitness Tracker",
    category: categories.healthFitness,
    description: "Track your health metrics with this stylish fitness tracker.",
    price: 6999,
    rating: 4.8,
    image: "/images/fitness_tracker_watch.jpeg",
  },
  {
    id: 153,
    title: "Pull-Up Bar",
    category: categories.sportsFitness,
    description: "Install this pull-up bar at home for upper body workouts.",
    price: 2499,
    rating: 4.5,
    image: "/images/pull_up_bar.jpeg",
  },
  {
    id: 154,
    title: "Knee Pads",
    category: categories.sportsFitness,
    description:
      "Protect your knees during workouts with these durable knee pads.",
    price: 1499,
    rating: 4.3,
    image: "/images/knee_pads.jpeg",
  },
  {
    id: 155,
    title: "Hot pot",
    category: categories.sportsFitness,
    description: "Improve your balance and strength with this Hot pot.",
    price: 1999,
    rating: 4.7,
    image: "/images/WhatsApp Image 2024-12-03 at 9.32.09 PM.jpeg",
  },
  {
    id: 156,
    title: "Balance Board",
    category: categories.sportsFitness,
    description: "Improve your core strength with this balance board.",
    price: 2499,
    rating: 4.4,
    image: "/images/WhatsApp Image 2024-12-03 at 9.35.03 PM (1).jpeg",
  },
  {
    id: 157,
    title: "New Goggles",
    category: categories.sportsFitness,
    description: "Anti-fog swimming goggles for a clear underwater view.",
    price: 999,
    rating: 4.3,
    image: "/images/swimming_goggles.jpeg",
  },
  {
    id: 158,
    title: "Golf Set",
    category: categories.sportsFitness,
    description: "Complete golf set for beginners and professionals.",
    price: 15999,
    rating: 4.6,
    image: "/images/golf_set.jpeg",
  },
  {
    id: 159,
    title: "Spoon set",
    category: categories.sportsFitness,
    description: "Durable fitness ball for exercises and stretching.",
    price: 1999,
    rating: 4.5,
    image: "/images/spoonset.jpeg",
  },
  {
    id: 160,
    title: "Punching Bag",
    category: categories.sportsFitness,
    description: "Heavy-duty punching bag for home boxing training.",
    price: 9999,
    rating: 4.7,
    image: "/images/bag.jpeg",
  },
  {
    id: 161,
    title: "Ceramic Dinner Plate",
    category: categories.crockery,
    description: "Elegant ceramic dinner plate for formal dining.",
    price: 2499,
    rating: 4.7,
    image: "/images/ceramic_plate.jpeg",
  },
  {
    id: 162,
    title: "Glass Salad Bowl",
    category: categories.crockery,
    description:
      "Transparent glass salad bowl perfect for serving fresh salads.",
    price: 1499,
    rating: 4.5,
    image: "/images/salad_bowl.jpeg",
  },
  {
    id: 163,
    title: "Soup Bowl Set",
    category: categories.crockery,
    description: "Set of 4 durable soup bowls with elegant design.",
    price: 1999,
    rating: 4.6,
    image: "/images/soup_bowl_set.jpeg",
  },
  {
    id: 164,
    title: "Ceramic Teapot",
    category: categories.crockery,
    description: "Charming ceramic teapot with a floral design.",
    price: 3499,
    rating: 4.8,
    image: "/images/teapot.jpeg",
  },
  {
    id: 165,
    title: "Stainless Steel Cup Set",
    category: categories.crockery,
    description: "Rust-resistant stainless steel cups, set of 6.",
    price: 1599,
    rating: 4.4,
    image: "/images/steel_cups.jpeg",
  },
  {
    id: 166,
    title: "Porcelain Mug",
    category: categories.crockery,
    description: "Classic porcelain mug with intricate designs.",
    price: 999,
    rating: 4.7,
    image: "/images/porcelain_mug.jpeg",
  },
  {
    id: 167,
    title: "Glass Pitcher",
    category: categories.crockery,
    description: "Elegant glass pitcher for serving drinks and juices.",
    price: 1999,
    rating: 4.5,
    image: "/images/glass_pitcher.jpeg",
  },
  {
    id: 168,
    title: "Tea Set",
    category: categories.crockery,
    description: "Complete tea set with 4 cups and a teapot.",
    price: 4999,
    rating: 4.8,
    image: "/images/tea_set1.jpeg",
  },
  {
    id: 169,
    title: "Dinnerware Set",
    category: categories.crockery,
    description: "Complete dinnerware set with plates, bowls, and cups.",
    price: 5999,
    rating: 4.6,
    image: "/images/dinnerware_set.jpeg",
  },
  {
    id: 170,
    title: "Glass Dessert Cups",
    category: categories.crockery,
    description: "Set of 6 stylish glass dessert cups for sweet treats.",
    price: 2499,
    rating: 4.7,
    image: "/images/dessert_cups.jpeg",
  },
  {
    id: 171,
    title: "Bamboo Serving cup",
    category: categories.crockery,
    description: "Eco-friendly bamboo serving tray for meals and drinks.",
    price: 1599,
    rating: 4.5,
    image: "/images/wooden_cutting_board.jpeg",
  },
  {
    id: 172,
    title: "Wooden Cutting Board",
    category: categories.crockery,
    description: "Durable wooden cutting board for chopping and slicing.",
    price: 2999,
    rating: 4.6,
    image: "/images/bamboo_tray.jpeg",
  },
  {
    id: 173,
    title: "Chopping Board Set",
    category: categories.crockery,
    description: "Set of 3 chopping boards with non-slip grips.",
    price: 1999,
    rating: 4.7,
    image: "/images/chopping_board_set.jpeg",
  },
  {
    id: 174,
    title: "Stoneware Bowl Set",
    category: categories.crockery,
    description: "Set of 4 stoneware bowls for soups, cereals, and salads.",
    price: 2499,
    rating: 4.6,
    image: "/images/stoneware_bowls.jpeg",
  },
  {
    id: 175,
    title: "Ceramic Salt & Pepper Shaker",
    category: categories.crockery,
    description: "Stylish ceramic salt and pepper shaker set for your table.",
    price: 1299,
    rating: 4.4,
    image: "/images/salt_pepper_shaker.jpeg",
  },
  {
    id: 176,
    title: "Fruit Bowl",
    category: categories.crockery,
    description: "Elegant fruit bowl for displaying fresh fruits.",
    price: 1799,
    rating: 4.7,
    image: "/images/fruit_bowl.jpeg",
  },
  {
    id: 177,
    title: "Coffee Mug Set",
    category: categories.crockery,
    description: "Set of 4 colorful coffee mugs for your morning coffee.",
    price: 1999,
    rating: 4.6,
    image: "/images/coffee_mugs_set.jpeg",
  },
  {
    id: 178,
    title: "Porcelain Tea",
    category: categories.crockery,
    description: "Elegant porcelain tea cups with delicate floral designs.",
    price: 2499,
    rating: 4.7,
    image: "/images/porcelain_tea_cups.jpeg",
  },
  {
    id: 179,
    title: "Stoneware Mug",
    category: categories.crockery,
    description: "Rustic stoneware mug for hot beverages.",
    price: 1499,
    rating: 4.5,
    image: "/images/stoneware_mug.jpeg",
  },
  {
    id: 180,
    title: "Talmas Stand",
    category: categories.crockery,
    description: "Elegant cake stand for displaying cakes and pastries.",
    price: 3999,
    rating: 4.6,
    image: "/images/cake_stand.jpeg",
  },
  {
    id: 181,
    title: "Stone Set",
    category: categories.crockery,
    description: "Pizza stone set for baking crispy pizzas at home.",
    price: 3499,
    rating: 4.7,
    image: "/images/pizza_stone_set.jpeg",
  },
  {
    id: 182,
    title: "Glass Water Pitcher",
    category: categories.crockery,
    description: "Stylish glass water pitcher with a modern design.",
    price: 2499,
    rating: 4.6,
    image: "/images/glass_water_pitcher.jpeg",
  },
  {
    id: 183,
    title: "Cup and Saucer Set",
    category: categories.crockery,
    description: "Elegant cup and saucer set for serving tea and coffee.",
    price: 1999,
    rating: 4.5,
    image: "/images/cup_saucer_set.jpeg",
  },
  {
    id: 184,
    title: "Tea Infuser",
    category: categories.crockery,
    description: "Stainless steel tea infuser for brewing loose leaf tea.",
    price: 999,
    rating: 4.6,
    image: "/images/tea_infuser.jpeg",
  },
  {
    id: 185,
    title: "Glass Cake Dome",
    category: categories.crockery,
    description: "Elegant glass cake dome for showcasing cakes and desserts.",
    price: 2999,
    rating: 4.7,
    image: "/images/glass_cake_dome.jpeg",
  },
  {
    id: 186,
    title: "Charger set",
    category: categories.crockery,
    description: "Decorative charger plate for formal dining settings.",
    price: 1999,
    rating: 4.6,
    image: "/images/charger_plate.jpeg",
  },
  {
    id: 187,
    title: "Lemon Juicer",
    category: categories.crockery,
    description: "Manual lemon juicer for fresh juice extraction.",
    price: 899,
    rating: 4.5,
    image: "/images/lemon_juicer.jpeg",
  },
  {
    id: 188,
    title: "cookware",
    category: categories.crockery,
    description: "Wooden cheese board with built-in knife slots.",
    price: 3499,
    rating: 4.7,
    image: "/images/cheese_board.jpeg",
  },
  {
    id: 189,
    title: "Water bottle",
    category: categories.crockery,
    description: "Classic butter dish to keep your butter fresh.",
    price: 1299,
    rating: 4.6,
    image: "/images/butter_dish.jpeg",
  },
  {
    id: 190,
    title: "New Spoon Set",
    category: categories.crockery,
    description: "Elegant teacup set with matching saucers for tea time.",
    price: 2499,
    rating: 4.8,
    image: "/images/new.jpeg",
  },
];
